project:
  type: website
  output-dir: Homepage

website:
  title: "Hung Tran"
  favicon: "assets/gu-logo.png"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Academic Projects
        menu: 
          - text: "Clicks vs. Bricks: Demographic and Financial Drivers of Shopping Preferences"
            href: https://htran.georgetown.domains/5000-Project/ 
          - text: "Airbnb: What Factors Influence Price?"
            href: https://htran.georgetown.domains/5100-Project/ 
          - text: "Data Analysis & Viz of FAA Flight Data"
            href: https://htran.georgetown.domains/6300-Project/ 
    right:
      - icon: github
        href: https://github.com/hungtran10
        aria-label: GitHub 
      - icon: linkedin
        href: https://www.linkedin.com/in/hungtran8/
        aria-label: LinkedIn


format:
  html:
    theme: zephyr
    css: ./styles.css
    toc: true
    toc-location: left



